CREATE TABLE IF NOT EXISTS portfolios (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS companies (
  id SERIAL PRIMARY KEY,
  denue_id VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  activity VARCHAR(255),
  phone VARCHAR(50),
  email VARCHAR(100),
  website VARCHAR(255),
  address VARCHAR(255),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  portfolio_id INT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
  call_status VARCHAR(50) DEFAULT 'Pendiente',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
